/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

/**
 *
 * @author yeabsira
 */
public class AdminDashboard extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(AdminDashboard.class.getName());

    /**
     * Creates new form AdminDashboard
     */
    public AdminDashboard() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        addBookButton = new javax.swing.JButton();
        viewBooksButton = new javax.swing.JButton();
        issueBookButton = new javax.swing.JButton();
        returnBookButton = new javax.swing.JButton();
        viewIssuedButton = new javax.swing.JButton();
        logoutButton = new javax.swing.JButton();
        addUserButton = new javax.swing.JButton();
        approveRequestButton = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        statisticsButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel1.setText("ADMIN DASHBOARD");

        addBookButton.setBackground(new java.awt.Color(51, 153, 255));
        addBookButton.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        addBookButton.setForeground(new java.awt.Color(255, 255, 255));
        addBookButton.setText("Add Book");
        addBookButton.addActionListener(this::addBookButtonActionPerformed);

        viewBooksButton.setBackground(new java.awt.Color(51, 153, 255));
        viewBooksButton.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        viewBooksButton.setForeground(new java.awt.Color(255, 255, 255));
        viewBooksButton.setText("View Books");
        viewBooksButton.addActionListener(this::viewBooksButtonActionPerformed);

        issueBookButton.setBackground(new java.awt.Color(51, 153, 255));
        issueBookButton.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        issueBookButton.setForeground(new java.awt.Color(255, 255, 255));
        issueBookButton.setText("Issue Book");
        issueBookButton.addActionListener(this::issueBookButtonActionPerformed);

        returnBookButton.setBackground(new java.awt.Color(51, 153, 255));
        returnBookButton.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        returnBookButton.setForeground(new java.awt.Color(255, 255, 255));
        returnBookButton.setText("Return Book");
        returnBookButton.addActionListener(this::returnBookButtonActionPerformed);

        viewIssuedButton.setBackground(new java.awt.Color(51, 153, 255));
        viewIssuedButton.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        viewIssuedButton.setForeground(new java.awt.Color(255, 255, 255));
        viewIssuedButton.setText("View Issued Books");
        viewIssuedButton.addActionListener(this::viewIssuedButtonActionPerformed);

        logoutButton.setBackground(new java.awt.Color(0, 0, 0));
        logoutButton.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        logoutButton.setForeground(new java.awt.Color(255, 255, 255));
        logoutButton.setText("Logout");
        logoutButton.addActionListener(this::logoutButtonActionPerformed);

        addUserButton.setBackground(new java.awt.Color(51, 153, 255));
        addUserButton.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        addUserButton.setForeground(new java.awt.Color(255, 255, 255));
        addUserButton.setText("Add User");
        addUserButton.addActionListener(this::addUserButtonActionPerformed);

        approveRequestButton.setBackground(new java.awt.Color(51, 153, 255));
        approveRequestButton.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        approveRequestButton.setForeground(new java.awt.Color(255, 255, 255));
        approveRequestButton.setText("Approve Requests");
        approveRequestButton.addActionListener(this::approveRequestButtonActionPerformed);

        jButton1.setBackground(new java.awt.Color(51, 153, 255));
        jButton1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Return Approval");
        jButton1.addActionListener(this::jButton1ActionPerformed);

        statisticsButton.setBackground(new java.awt.Color(51, 153, 255));
        statisticsButton.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        statisticsButton.setForeground(new java.awt.Color(255, 255, 255));
        statisticsButton.setText("Statistics");
        statisticsButton.addActionListener(this::statisticsButtonActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(127, 127, 127)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(addBookButton, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(viewBooksButton, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(issueBookButton, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(returnBookButton, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(43, 43, 43)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(addUserButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(viewIssuedButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(approveRequestButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(133, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(logoutButton)
                        .addGap(276, 276, 276))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(statisticsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addBookButton)
                    .addComponent(viewIssuedButton))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(viewBooksButton)
                    .addComponent(addUserButton))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(issueBookButton)
                    .addComponent(approveRequestButton))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(returnBookButton)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addComponent(statisticsButton)
                .addGap(2, 2, 2)
                .addComponent(logoutButton)
                .addGap(28, 28, 28))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void issueBookButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_issueBookButtonActionPerformed
        // TODO add your handling code here:
        new IssueBookForm().setVisible(true);
    }//GEN-LAST:event_issueBookButtonActionPerformed

    private void viewBooksButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewBooksButtonActionPerformed
        // TODO add your handling code here:
        new AdminViewBooksForm().setVisible(true);
    }//GEN-LAST:event_viewBooksButtonActionPerformed

    private void addBookButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBookButtonActionPerformed
        // TODO add your handling code here:
        new AddBookForm().setVisible(true);
    }//GEN-LAST:event_addBookButtonActionPerformed

    private void returnBookButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_returnBookButtonActionPerformed
        // TODO add your handling code here:
        new ReturnBookForm().setVisible(true);
    }//GEN-LAST:event_returnBookButtonActionPerformed

    private void viewIssuedButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewIssuedButtonActionPerformed
        // TODO add your handling code here:
        new ViewIssuedBooksForm().setVisible(true);
    }//GEN-LAST:event_viewIssuedButtonActionPerformed

    private void logoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutButtonActionPerformed
        // TODO add your handling code here:
          new LoginForm().setVisible(true);

     dispose();
    }//GEN-LAST:event_logoutButtonActionPerformed

    private void addUserButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addUserButtonActionPerformed
        // TODO add your handling code here:
        new AdminAddUserForm().setVisible(true);
    }//GEN-LAST:event_addUserButtonActionPerformed

    private void approveRequestButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_approveRequestButtonActionPerformed
        // TODO add your handling code here:
        new ApprovalForm().setVisible(true);
    }//GEN-LAST:event_approveRequestButtonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        new ReturnApprovalForm().setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void statisticsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_statisticsButtonActionPerformed
        // TODO add your handling code here:
        new StatisticsForm().setVisible(true);
    }//GEN-LAST:event_statisticsButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new AdminDashboard().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addBookButton;
    private javax.swing.JButton addUserButton;
    private javax.swing.JButton approveRequestButton;
    private javax.swing.JButton issueBookButton;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton logoutButton;
    private javax.swing.JButton returnBookButton;
    private javax.swing.JButton statisticsButton;
    private javax.swing.JButton viewBooksButton;
    private javax.swing.JButton viewIssuedButton;
    // End of variables declaration//GEN-END:variables
}
