/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;

import javax.swing.table.DefaultTableModel;

import database.DBConnection;
import javax.swing.JOptionPane;

import javax.swing.table.DefaultTableModel;

/**
 *
 * @author yeabsira
 */
public class ApprovalForm extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ApprovalForm.class.getName());
    
    
    public void loadRequests() {

    try {

        Connection con =
                DBConnection.getConnection();

        String sql =
                "SELECT * FROM issue_requests";

        PreparedStatement pst =
                con.prepareStatement(sql);

        ResultSet rs =
                pst.executeQuery();

        DefaultTableModel model =
        (DefaultTableModel) requestTable.getModel();

        model.setRowCount(0);

        while (rs.next()) {

            Object[] row = {

                rs.getInt("request_id"),
                rs.getInt("user_id"),
                rs.getInt("book_id"),
                rs.getInt("days"),
                rs.getDate("issue_date")
            };

            model.addRow(row);
        }

    } catch (Exception e) {

        System.out.println(e);
    }
}

    /**
     * Creates new form ApprovalForm
     */
    public ApprovalForm() {
        initComponents();
        loadRequests();

setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        requestTable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        searchButton = new javax.swing.JButton();
        searchUserField = new javax.swing.JTextField();
        approveButton = new javax.swing.JButton();
        refreshButton = new javax.swing.JButton();
        backButton = new javax.swing.JButton();
        declineButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        requestTable.setBackground(new java.awt.Color(51, 204, 255));
        requestTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Request ID", "User ID", "Book ID", "Days", "Issue Date"
            }
        ));
        jScrollPane1.setViewportView(requestTable);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel1.setText("Approval");

        searchButton.setBackground(new java.awt.Color(51, 153, 255));
        searchButton.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        searchButton.setForeground(new java.awt.Color(255, 255, 255));
        searchButton.setText("search");
        searchButton.addActionListener(this::searchButtonActionPerformed);

        approveButton.setBackground(new java.awt.Color(51, 153, 255));
        approveButton.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        approveButton.setForeground(new java.awt.Color(255, 255, 255));
        approveButton.setText("approve");
        approveButton.addActionListener(this::approveButtonActionPerformed);

        refreshButton.setBackground(new java.awt.Color(51, 153, 255));
        refreshButton.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        refreshButton.setForeground(new java.awt.Color(255, 255, 255));
        refreshButton.setText("refresh");
        refreshButton.addActionListener(this::refreshButtonActionPerformed);

        backButton.setBackground(new java.awt.Color(51, 153, 255));
        backButton.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        backButton.setForeground(new java.awt.Color(255, 255, 255));
        backButton.setText("Back");
        backButton.addActionListener(this::backButtonActionPerformed);

        declineButton.setBackground(new java.awt.Color(255, 0, 51));
        declineButton.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        declineButton.setForeground(new java.awt.Color(255, 255, 255));
        declineButton.setText("Decline");
        declineButton.addActionListener(this::declineButtonActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 567, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(138, 138, 138)
                                .addComponent(refreshButton)))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(searchButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(searchUserField, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(approveButton)
                        .addGap(29, 29, 29)
                        .addComponent(declineButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(backButton)
                        .addGap(21, 21, 21))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(refreshButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jLabel1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searchButton)
                    .addComponent(searchUserField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(approveButton)
                    .addComponent(backButton)
                    .addComponent(declineButton))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void searchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchButtonActionPerformed
        // TODO add your handling code here:
        try {

    String userId =
            searchUserField.getText();

    Connection con =
            DBConnection.getConnection();

    String sql =
    "SELECT * FROM issue_requests WHERE user_id=?";

    PreparedStatement pst =
            con.prepareStatement(sql);

    pst.setInt(1,
            Integer.parseInt(userId));

    ResultSet rs =
            pst.executeQuery();

    DefaultTableModel model =
    (DefaultTableModel) requestTable.getModel();

    model.setRowCount(0);

    while (rs.next()) {

        Object[] row = {

            rs.getInt("request_id"),
            rs.getInt("user_id"),
            rs.getInt("book_id"),
            rs.getInt("days"),
            rs.getDate("issue_date")
        };

        model.addRow(row);
    }

} catch (Exception e) {

    System.out.println(e);
}
    }//GEN-LAST:event_searchButtonActionPerformed

    private void approveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_approveButtonActionPerformed
        // TODO add your handling code here:
        try {

    int selectedRow =
            requestTable.getSelectedRow();

    if (selectedRow == -1) {

        JOptionPane.showMessageDialog(this,
                "Please Select Request");

        return;
    }

    DefaultTableModel model =
    (DefaultTableModel) requestTable.getModel();

    int requestId =
            Integer.parseInt(
            model.getValueAt(selectedRow, 0).toString());

    int userId =
            Integer.parseInt(
            model.getValueAt(selectedRow, 1).toString());

    int bookId =
            Integer.parseInt(
            model.getValueAt(selectedRow, 2).toString());

    int days =
            Integer.parseInt(
            model.getValueAt(selectedRow, 3).toString());

    java.sql.Date issueDate =
    java.sql.Date.valueOf(
    model.getValueAt(selectedRow, 4).toString());

    Connection con =
            DBConnection.getConnection();

    // INSERT INTO issued_books
    String insertSql =
    "INSERT INTO issued_books(user_id, book_id, days, issue_date) VALUES (?, ?, ?, ?)";

    PreparedStatement pst1 =
            con.prepareStatement(insertSql);

    pst1.setInt(1, userId);
    pst1.setInt(2, bookId);
    pst1.setInt(3, days);
    pst1.setDate(4, issueDate);

    pst1.executeUpdate();

    // DECREASE BOOK QUANTITY
    String updateSql =
    "UPDATE books SET quantity = quantity - 1 WHERE book_id=?";

    PreparedStatement pst2 =
            con.prepareStatement(updateSql);

    pst2.setInt(1, bookId);

    pst2.executeUpdate();

    // DELETE REQUEST
    String deleteSql =
    "DELETE FROM issue_requests WHERE request_id=?";

    PreparedStatement pst3 =
            con.prepareStatement(deleteSql);

    pst3.setInt(1, requestId);

    pst3.executeUpdate();

    JOptionPane.showMessageDialog(this,
            "Request Approved");

    loadRequests();

} catch (Exception e) {

    JOptionPane.showMessageDialog(this, e);
}
    }//GEN-LAST:event_approveButtonActionPerformed

    private void refreshButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshButtonActionPerformed
        // TODO add your handling code here:
         loadRequests();
        
    }//GEN-LAST:event_refreshButtonActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        // TODO add your handling code here:
          new AdminDashboard().setVisible(true);

     dispose();
    }//GEN-LAST:event_backButtonActionPerformed

    private void declineButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_declineButtonActionPerformed
        // TODO add your handling code here:
        try {

    int selectedRow =
            requestTable.getSelectedRow();

    if (selectedRow == -1) {

        JOptionPane.showMessageDialog(this,
                "Select Request");

        return;
    }

    DefaultTableModel model =
    (DefaultTableModel) requestTable.getModel();

    int requestId =
    Integer.parseInt(
    model.getValueAt(selectedRow, 0).toString());

    Connection con =
            DBConnection.getConnection();

    String sql =
    "DELETE FROM issue_requests WHERE request_id=?";

    PreparedStatement pst =
            con.prepareStatement(sql);

    pst.setInt(1, requestId);

    pst.executeUpdate();

    JOptionPane.showMessageDialog(this,
            "Request Declined");

    loadRequests();

} catch (Exception e) {

    JOptionPane.showMessageDialog(this, e);
}
    }//GEN-LAST:event_declineButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new ApprovalForm().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton approveButton;
    private javax.swing.JButton backButton;
    private javax.swing.JButton declineButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton refreshButton;
    private javax.swing.JTable requestTable;
    private javax.swing.JButton searchButton;
    private javax.swing.JTextField searchUserField;
    // End of variables declaration//GEN-END:variables
}
