/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;

import javax.swing.table.DefaultTableModel;

import database.DBConnection;
import javax.swing.JOptionPane;

/**
 *
 * @author yeabsira
 */
public class ReturnApprovalForm extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ReturnApprovalForm.class.getName());
    
    public void loadReturnRequests() {

    try {

        Connection con =
                DBConnection.getConnection();

        String sql =
                "SELECT * FROM return_requests";

        PreparedStatement pst =
                con.prepareStatement(sql);

        ResultSet rs =
                pst.executeQuery();

        DefaultTableModel model =
        (DefaultTableModel) returnTable.getModel();

        model.setRowCount(0);

        while (rs.next()) {

            Object[] row = {

                rs.getInt("return_id"),
                rs.getInt("user_id"),
                rs.getInt("book_id"),
                rs.getDate("request_date")
            };

            model.addRow(row);
        }

    } catch (Exception e) {

        System.out.println(e);
    }
}

    /**
     * Creates new form ReturnApprovalForm
     */
    public ReturnApprovalForm() {

    initComponents();

    loadReturnRequests();

    setLocationRelativeTo(null);
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        returnTable = new javax.swing.JTable();
        searchButton = new javax.swing.JButton();
        searchUserField = new javax.swing.JTextField();
        approveReturnButton = new javax.swing.JButton();
        refreshButton = new javax.swing.JButton();
        backButton = new javax.swing.JButton();
        declineButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel1.setText("ReturnApproval");

        returnTable.setBackground(new java.awt.Color(0, 204, 255));
        returnTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Return ID", "User ID", "Book ID", "Request Date"
            }
        ));
        jScrollPane1.setViewportView(returnTable);

        searchButton.setBackground(new java.awt.Color(51, 153, 255));
        searchButton.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        searchButton.setForeground(new java.awt.Color(255, 255, 255));
        searchButton.setText("search");
        searchButton.addActionListener(this::searchButtonActionPerformed);

        approveReturnButton.setBackground(new java.awt.Color(51, 153, 255));
        approveReturnButton.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        approveReturnButton.setForeground(new java.awt.Color(255, 255, 255));
        approveReturnButton.setText("approve");
        approveReturnButton.addActionListener(this::approveReturnButtonActionPerformed);

        refreshButton.setBackground(new java.awt.Color(51, 153, 255));
        refreshButton.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        refreshButton.setForeground(new java.awt.Color(255, 255, 255));
        refreshButton.setText("refresh");
        refreshButton.addActionListener(this::refreshButtonActionPerformed);

        backButton.setBackground(new java.awt.Color(51, 153, 255));
        backButton.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        backButton.setForeground(new java.awt.Color(255, 255, 255));
        backButton.setText("Back");
        backButton.addActionListener(this::backButtonActionPerformed);

        declineButton.setBackground(new java.awt.Color(255, 51, 51));
        declineButton.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        declineButton.setForeground(new java.awt.Color(255, 255, 255));
        declineButton.setText("Decline ");
        declineButton.addActionListener(this::declineButtonActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(searchButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(searchUserField, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(approveReturnButton)
                        .addGap(18, 18, 18)
                        .addComponent(declineButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(backButton)
                        .addGap(15, 15, 15))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 550, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(126, 126, 126)
                        .addComponent(refreshButton)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(15, Short.MAX_VALUE)
                        .addComponent(refreshButton))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searchButton)
                    .addComponent(searchUserField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(approveReturnButton)
                    .addComponent(backButton)
                    .addComponent(declineButton))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void searchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchButtonActionPerformed
        // TODO add your handling code here:
        try {

    String userId =
            searchUserField.getText();

    Connection con =
            DBConnection.getConnection();

    String sql =
    "SELECT * FROM return_requests WHERE user_id=?";

    PreparedStatement pst =
            con.prepareStatement(sql);

    pst.setInt(1,
            Integer.parseInt(userId));

    ResultSet rs =
            pst.executeQuery();

    DefaultTableModel model =
    (DefaultTableModel) returnTable.getModel();

    model.setRowCount(0);

    while (rs.next()) {

        Object[] row = {

            rs.getInt("return_id"),
            rs.getInt("user_id"),
            rs.getInt("book_id"),
            rs.getDate("request_date")
        };

        model.addRow(row);
    }

} catch (Exception e) {

    JOptionPane.showMessageDialog(this, e);
}
    }//GEN-LAST:event_searchButtonActionPerformed

    private void approveReturnButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_approveReturnButtonActionPerformed
        // TODO add your handling code here:
        try {

    int selectedRow =
            returnTable.getSelectedRow();

    if (selectedRow == -1) {

        JOptionPane.showMessageDialog(this,
                "Select Request");

        return;
    }

    DefaultTableModel model =
    (DefaultTableModel) returnTable.getModel();

    int returnId =
    Integer.parseInt(
    model.getValueAt(selectedRow, 0).toString());

    int userId =
    Integer.parseInt(
    model.getValueAt(selectedRow, 1).toString());

    int bookId =
    Integer.parseInt(
    model.getValueAt(selectedRow, 2).toString());

    Connection con =
            DBConnection.getConnection();

    // REMOVE FROM issued_books
    String deleteIssued =
    "DELETE FROM issued_books WHERE user_id=? AND book_id=?";

    PreparedStatement pst1 =
            con.prepareStatement(deleteIssued);

    pst1.setInt(1, userId);
    pst1.setInt(2, bookId);

    pst1.executeUpdate();

    // INCREASE QUANTITY
    String updateBook =
    "UPDATE books SET quantity = quantity + 1 WHERE book_id=?";

    PreparedStatement pst2 =
            con.prepareStatement(updateBook);

    pst2.setInt(1, bookId);

    pst2.executeUpdate();

    // DELETE RETURN REQUEST
    String deleteRequest =
    "DELETE FROM return_requests WHERE return_id=?";

    PreparedStatement pst3 =
            con.prepareStatement(deleteRequest);

    pst3.setInt(1, returnId);

    pst3.executeUpdate();

    JOptionPane.showMessageDialog(this,
            "Return Approved");

    loadReturnRequests();

} catch (Exception e) {

    JOptionPane.showMessageDialog(this, e);
}
    }//GEN-LAST:event_approveReturnButtonActionPerformed

    private void refreshButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshButtonActionPerformed
        // TODO add your handling code here:
        loadReturnRequests();
    }//GEN-LAST:event_refreshButtonActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        // TODO add your handling code here:
          new AdminDashboard().setVisible(true);

     dispose();
    }//GEN-LAST:event_backButtonActionPerformed

    private void declineButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_declineButtonActionPerformed
        // TODO add your handling code here:
        try {

    int selectedRow =
            returnTable.getSelectedRow();

    if (selectedRow == -1) {

        JOptionPane.showMessageDialog(this,
                "Select Return Request");

        return;
    }

    DefaultTableModel model =
    (DefaultTableModel) returnTable.getModel();

    int returnId =
    Integer.parseInt(
    model.getValueAt(selectedRow, 0).toString());

    Connection con =
            DBConnection.getConnection();

    String sql =
    "DELETE FROM return_requests WHERE return_id=?";

    PreparedStatement pst =
            con.prepareStatement(sql);

    pst.setInt(1, returnId);

    pst.executeUpdate();

    JOptionPane.showMessageDialog(this,
            "Return Request Declined");

    loadReturnRequests();

} catch (Exception e) {

    JOptionPane.showMessageDialog(this, e);
}
    }//GEN-LAST:event_declineButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new ReturnApprovalForm().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton approveReturnButton;
    private javax.swing.JButton backButton;
    private javax.swing.JButton declineButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton refreshButton;
    private javax.swing.JTable returnTable;
    private javax.swing.JButton searchButton;
    private javax.swing.JTextField searchUserField;
    // End of variables declaration//GEN-END:variables
}
