/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;

import database.DBConnection;

/**
 *
 * @author yeabsira
 */
public class StatisticsForm extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(StatisticsForm.class.getName());
    
    public void loadTotalBooks() {

    try {

        Connection con =
                DBConnection.getConnection();

        String sql =
                "SELECT COUNT(*) FROM books";

        PreparedStatement pst =
                con.prepareStatement(sql);

        ResultSet rs =
                pst.executeQuery();

        if (rs.next()) {

            totalBooksLabel.setText(
                    rs.getString(1));
        }

    } catch (Exception e) {

        System.out.println(e);
    }
}
    public void loadTotalUsers() {

    try {

        Connection con =
                DBConnection.getConnection();

        String sql =
        "SELECT COUNT(*) FROM users WHERE role='user'";

        PreparedStatement pst =
                con.prepareStatement(sql);

        ResultSet rs =
                pst.executeQuery();

        if (rs.next()) {

            totalUsersLabel.setText(
                    rs.getString(1));
        }

    } catch (Exception e) {

        System.out.println(e);
    }
}
    public void loadIssuedBooks() {

    try {

        Connection con =
                DBConnection.getConnection();

        String sql =
        "SELECT COUNT(*) FROM issued_books";

        PreparedStatement pst =
                con.prepareStatement(sql);

        ResultSet rs =
                pst.executeQuery();

        if (rs.next()) {

            issuedBooksLabel.setText(
                    rs.getString(1));
        }

    } catch (Exception e) {

        System.out.println(e);
    }
}
    public void loadPendingIssues() {

    try {

        Connection con =
                DBConnection.getConnection();

        String sql =
        "SELECT COUNT(*) FROM issue_requests";

        PreparedStatement pst =
                con.prepareStatement(sql);

        ResultSet rs =
                pst.executeQuery();

        if (rs.next()) {

            pendingIssueLabel.setText(
                    rs.getString(1));
        }

    } catch (Exception e) {

        System.out.println(e);
    }
}
    public void loadPendingReturns() {

    try {

        Connection con =
                DBConnection.getConnection();

        String sql =
        "SELECT COUNT(*) FROM return_requests";

        PreparedStatement pst =
                con.prepareStatement(sql);

        ResultSet rs =
                pst.executeQuery();

        if (rs.next()) {

            pendingReturnLabel.setText(
                    rs.getString(1));
        }

    } catch (Exception e) {

        System.out.println(e);
    }
}
    public void loadOverdueBooks() {

    try {

        Connection con =
                DBConnection.getConnection();

        String sql =
        "SELECT COUNT(*) FROM issued_books " +
        "WHERE DATEDIFF(CURDATE(), issue_date) > days";

        PreparedStatement pst =
                con.prepareStatement(sql);

        ResultSet rs =
                pst.executeQuery();

        if (rs.next()) {

            overdueLabel.setText(
                    rs.getString(1));
        }

    } catch (Exception e) {

        System.out.println(e);
    }
}

    /**
     * Creates new form StatisticsForm
     */
    public StatisticsForm() {

    initComponents();

    loadTotalBooks();
    loadTotalUsers();
    loadIssuedBooks();
    loadPendingIssues();
    loadPendingReturns();
    loadOverdueBooks();

    setLocationRelativeTo(null);
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        totalBooksLabel = new javax.swing.JLabel();
        totalUsersLabel = new javax.swing.JLabel();
        issuedBooksLabel = new javax.swing.JLabel();
        pendingIssueLabel = new javax.swing.JLabel();
        overdueLabel = new javax.swing.JLabel();
        pendingReturnLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        backButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        totalBooksLabel.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        totalBooksLabel.setText(" Total Books ");

        totalUsersLabel.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        totalUsersLabel.setText("Total Users ");

        issuedBooksLabel.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        issuedBooksLabel.setText("Issued Books");

        pendingIssueLabel.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        pendingIssueLabel.setText("pendingIssue");

        overdueLabel.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        overdueLabel.setText("Overdue Books");

        pendingReturnLabel.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        pendingReturnLabel.setText("pendingReturn");

        jLabel1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel1.setText(" Total Books :");

        jLabel2.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel2.setText("Total Users :");

        jLabel3.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel3.setText("Issued Books :");

        jLabel4.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel4.setText("pendingIssue :");

        jLabel5.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel5.setText("pendingReturn :");

        jLabel6.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel6.setText("Overdue Books :");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pendingReturnLabel)
                            .addComponent(overdueLabel)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(34, 34, 34)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pendingIssueLabel)
                            .addComponent(totalUsersLabel)
                            .addComponent(totalBooksLabel)
                            .addComponent(issuedBooksLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(64, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(totalBooksLabel)
                    .addComponent(jLabel1))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(totalUsersLabel)
                    .addComponent(jLabel2))
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(issuedBooksLabel)
                    .addComponent(jLabel3))
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pendingIssueLabel)
                    .addComponent(jLabel4))
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pendingReturnLabel)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(overdueLabel)
                    .addComponent(jLabel6))
                .addGap(31, 31, 31))
        );

        backButton.setBackground(new java.awt.Color(51, 153, 255));
        backButton.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        backButton.setForeground(new java.awt.Color(255, 255, 255));
        backButton.setText("Back");
        backButton.addActionListener(this::backButtonActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 78, Short.MAX_VALUE)
                .addComponent(backButton)
                .addGap(57, 57, 57))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(backButton)
                .addGap(21, 21, 21))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        // TODO add your handling code here:
          new AdminDashboard().setVisible(true);

     dispose();
    }//GEN-LAST:event_backButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new StatisticsForm().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    private javax.swing.JLabel issuedBooksLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel overdueLabel;
    private javax.swing.JLabel pendingIssueLabel;
    private javax.swing.JLabel pendingReturnLabel;
    private javax.swing.JLabel totalBooksLabel;
    private javax.swing.JLabel totalUsersLabel;
    // End of variables declaration//GEN-END:variables
}
